# Generated by Django 3.0.8 on 2020-08-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('layout', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ip', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=150)),
                ('morada', models.CharField(max_length=150)),
                ('id_equipamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguradroRouter.Equipamentos')),
            ],
        ),
    ]
